// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRrHI6HGCkatBn84lJSW-7w_TMqSAOFo',
    appId: '1:325409991778:web:2513ef93d6048111a0b53b',
    messagingSenderId: '325409991778',
    projectId: 'test-1-22cd4',
    authDomain: 'test-1-22cd4.firebaseapp.com',
    storageBucket: 'test-1-22cd4.appspot.com',
    measurementId: 'G-Z303L1FSMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6atQMnpH6aucbbLTakcGQGVrdR58Unrk',
    appId: '1:325409991778:android:59718a9f54879a9aa0b53b',
    messagingSenderId: '325409991778',
    projectId: 'test-1-22cd4',
    storageBucket: 'test-1-22cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMIy7JvP7KuFV7TLxu2UoaA41SHgovojU',
    appId: '1:325409991778:ios:affc799665be51f2a0b53b',
    messagingSenderId: '325409991778',
    projectId: 'test-1-22cd4',
    storageBucket: 'test-1-22cd4.appspot.com',
    iosClientId: '325409991778-gb09vpmktkcaqupun48f58jgbbul5l2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.nCatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMIy7JvP7KuFV7TLxu2UoaA41SHgovojU',
    appId: '1:325409991778:ios:a7e41d490be3d597a0b53b',
    messagingSenderId: '325409991778',
    projectId: 'test-1-22cd4',
    storageBucket: 'test-1-22cd4.appspot.com',
    iosClientId: '325409991778-v09p9nativa5t3sc11i1rpk1cv8jf308.apps.googleusercontent.com',
    iosBundleId: 'com.example.nCatch.RunnerTests',
  );
}
